Models/Player.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Game.Models
{
    public class Player
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Nickname { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Status { get; set; }
        public string Rating{get; set;}


        [ForeignKey("Role_id")]
        public Role Role { get; set; }
        [DisplayName("Role")]
        public int Role_id { get; set; }

        [ForeignKey("Team_id")]
        public Team Team { get; set; }
        [DisplayName("Team")]
        public int Team_id { get; set; }



    }
}

Controllers/PlayerController.cs
using Game.Data;
using Game.Models;
using Game.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace Game.Controllers
{
    public class PlayerController : Controller
    {
        public readonly DataDbContext _db;

        public PlayerController(DataDbContext db)
        {
            _db = db;
        }


        [Authorize(Roles = "admin, moderator, user")]
        public IActionResult Index()
        {
            IEnumerable<Player> objList = _db.Players;

            foreach (var obj in objList)
            {
                obj.Role = _db.Roles.FirstOrDefault(u => u.Id == obj.Role_id);
                obj.Team = _db.Teams.FirstOrDefault(u => u.Id == obj.Team_id);

            }

            return View(objList);
        }

        // GET-Create
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {

            PlayerVM playerVM = new PlayerVM()
            {
                Player = new Player(),
                TDDRole = _db.Roles.Select(i => new SelectListItem
                {
                    Text = i.Rolename,
                    Value = i.Id.ToString()
                }),
                TDDTeam = _db.Teams.Select(i => new SelectListItem
                {
                    Text = i.TeamName,
                    Value = i.Id.ToString()
                })
            };

            return View(playerVM);
        }

        // POST-Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public IActionResult Create(PlayerVM obj)
        {
            if (ModelState.IsValid)
            {
                //obj.ExpenseTypeId = 1;
                _db.Players.Add(obj.Player);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);

        }

        // GET Delete
        [Authorize(Roles = "admin")]
        public IActionResult Delete(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Players.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);

        }

        // POST Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Players.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Players.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }

        // GET Update
        [Authorize(Roles = "admin, moderator")]
        public IActionResult Update(int? id)
        {
            PlayerVM playerVM = new PlayerVM()
            {
                Player = new Player(),
                TDDRole = _db.Roles.Select(i => new SelectListItem
                {
                    Text = i.Rolename,
                    Value = i.Id.ToString()
                }),
                TDDTeam = _db.Teams.Select(i => new SelectListItem
                {
                    Text = i.TeamName,
                    Value = i.Id.ToString()
                })
            };

            if (id == null || id == 0)
            {
                return NotFound();
            }
            playerVM.Player = _db.Players.Find(id);
            if (playerVM.Player == null)
            {
                return NotFound();
            }
            return View(playerVM);

        }

        // POST UPDATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin, moderator")]
        public IActionResult Update(PlayerVM obj)
        {
            if (ModelState.IsValid)
            {
                _db.Players.Update(obj.Player);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);

        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var player = await _db.Players.Include(b => b.Role).Include(c => c.Team)
            .FirstOrDefaultAsync(m => m.Id == id);

            if (player == null)
            {
                return NotFound();
            }

            return View(player);

        }
    }
}

Views/Player/Create.cshtml
@model Game.Models.ViewModels.PlayerVM

<form method="post" asp-action="Create">
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Добавить игрока</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="Player.Nickname"></label>
                        <input asp-for="Player.Nickname" class="form-control" />
                        <span asp-validation-for="Player.Nickname" class="text-danger"></span>
                    </div>
                    <div class="col-6">
                        <label asp-for="Player.Name"></label>
                        <input asp-for="Player.Name" class="form-control" />
                        <span asp-validation-for="Player.Name" class="text-danger"></span>
                    </div>
                    <div class="col-6">
                        <label asp-for="Player.Surname"></label>
                        <input asp-for="Player.Surname" class="form-control" />
                        <span asp-validation-for="Player.Surname" class="text-danger"></span>
                    </div>
                    <div class="col-6">
                        <label asp-for="Player.Rating"></label>
                        <input asp-for="Player.Rating" class="form-control" />
                        <span asp-validation-for="Player.Rating" class="text-danger"></span>
                    </div>
                    <div class="col-6">
                        <label asp-for="Player.Status"></label>
                        <input asp-for="Player.Status" class="form-control" />
                        <span asp-validation-for="Player.Status" class="text-danger"></span>
                    </div>

                    <div class="col-4">
                        <label asp-for="Player.Team"></label>
                        <select asp-for="Player.Team_id" asp-items="@Model.TDDTeam" class="form-control">
                            <option selected>--Выбрать команду--</option>
                        </select>
                        <span asp-validation-for="Player.Team_id" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <label asp-for="Player.Role"></label>
                        <select asp-for="Player.Role_id" asp-items="@Model.TDDRole" class="form-control">
                            <option selected>--Выберите роль--</option>
                        </select>
                        <span asp-validation-for="Player.Role_id" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Player/Delete.cshtml
@model Game.Models.Player

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Удалить игрока</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="Nickname"></label>
                    </div>
                    <div class="col-6">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-6">
                        <label asp-for="Surname"></label>
                    </div>
                    <div class="col-6">
                        <label asp-for="Rating"></label>
                    </div>
                    <div class="col-6">
                        <label asp-for="Status"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <input asp-for="Nickname" class="form-control" />
                    <span asp-validation-for="Nickname" class="text-danger"></span>
                </div>
                <div class="form-group row">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="col-6">
                    <input asp-for="Surname" class="form-control" />
                    <span asp-validation-for="Surname" class="text-danger"></span>
                </div>
                <div class="col-6">
                    <input asp-for="Rating" class="form-control" />
                    <span asp-validation-for="Rating" class="text-danger"></span>
                </div>
                <div class="form-group row">
                    <input asp-for="Status" class="form-control" />
                    <span asp-validation-for="Status" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-8 offset-2 row">
                    <div class="col">
                        <input type="submit" class="btn btn-danger w-75" value="Delete" />
                    </div>
                    <div class="col">
                        <a asp-action="Index" class="btn btn-success w-75">Back</a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Player/Index.cshtml
@model IEnumerable<Game.Models.Player>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Список игроков</h2>
        </div>
        @if(User.IsInRole("admin") || User.IsInRole("moderator"))
        {
        <div class="col-6 text-right">
            <a asp-controller="Player" asp-action="Create" class="btn btn-primary">Добавить нового игрока</a>
        </div>
        }
    </div>
    <br />

    @if (Model.Count() > 0)
    {
    <div class=" container overflow-hidden">
        <div class="row">
            @foreach (var obj in Model)
            {<div class="col-6">

                <div class="card p-3 my-2 border bg-light">
                    <h4>@obj.Nickname</h4>
                    <div>
                        <section>
                            <div class="row">
                                <div class="col-md-8 col-lg-3">
                                    <div class="row">
                                        <aside class="col-sm-6 col-md-12 p-4">
                                            <img src="~/images/player.jpg" class="img-thumbnail" alt="...">
                                        </aside>
                                    </div>
                                </div>
                                <main>
                                    Имя: @obj.Name<br /><br />
                                    Фамилия: @obj.Surname<br /><br />
                                    Статус:@obj.Status<br /><br />
                                    Рейтинг:@obj.Rating<br /><br />
                                    Команда:@obj.Team.TeamName<br /><br />
                                    Роль:@obj.Role.Rolename<br /><br />
                                </main>
                            </div>
                        </section>
                    </div>
                    <div class="w-100 btn-group" role="group">
                        @if(User.IsInRole("admin") || User.IsInRole("moderator"))
                        {
                        <a asp-controller="Player" asp-action="Update" asp-route-Id="@obj.Id" class="btn btn-primary mx-1 ">Изменить</a>
                        }
                        @if(User.IsInRole("admin"))
                        {
                        <a asp-controller="Player" asp-action="Delete" asp-route-Id="@obj.Id" class="btn btn-danger mx-1">Удалить</a>
                        }
                    </div>
                </div>
            </div>
            }
        </div>
    </div>
    }
    else
    {
    <p>No items created yet</p>
    }

</div>

Views/Player/Update.cshtml
@model Game.Models.ViewModels.PlayerVM

<form method="post" asp-action="Update">
    <input asp-for="Player.Id" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Обновить игрока</h2>
        </div>
        <div class="form-group row">
            <div class="col-6">
                <label asp-for="Player.Nickname"></label>
                <input asp-for="Player.Nickname" class="form-control" />
                <span asp-validation-for="Player.Nickname" class="text-danger"></span>
            </div>
            <div class="col-6">
                <label asp-for="Player.Name"></label>
                <input asp-for="Player.Name" class="form-control" />
                <span asp-validation-for="Player.Name" class="text-danger"></span>
            </div>
            <div class="col-6">
                <label asp-for="Player.Surname"></label>
                <input asp-for="Player.Surname" class="form-control" />
                <span asp-validation-for="Player.Surname" class="text-danger"></span>
            </div>
            <div class="col-6">
                <label asp-for="Player.Status"></label>
                <input asp-for="Player.Status" class="form-control" />
                <span asp-validation-for="Player.Status" class="text-danger"></span>
            </div>
            <div class="col-6">
                <label asp-for="Player.Rating"></label>
                <input asp-for="Player.Rating" class="form-control" />
                <span asp-validation-for="Player.Rating" class="text-danger"></span>
            </div>
            <div class="col-4">
                <label asp-for="Player.Team"></label>
                <select asp-for="Player.Team_id" asp-items="@Model.TDDTeam" class="form-control">
                    <option selected>--Выберите команду--</option>
                </select>
                <span asp-validation-for="Player.Team_id" class="text-danger"></span>
            </div>
            <div class="col-4">
                <label asp-for="Player.Role"></label>
                <select asp-for="Player.Role_id" asp-items="@Model.TDDRole" class="form-control">
                    <option selected>--Выберите роль--</option>
                </select>
                <span asp-validation-for="Player.Role_id" class="text-danger"></span>
            </div>
            <div class="container">
                <div class="row">
                    <div class="col">
                        <input type="submit" class="btn btn-info w-75" value="Update" />
                    </div>
                    <div class="col">
                        <a asp-action="Index" class="btn btn-danger w-75">Back</a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}