Controllers/PlatformController.cs
using Game.Data;
using Game.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace Game.Controllers
{
    public class PlatformController : Controller
    {
        private readonly DataDbContext _db;

        public PlatformController(DataDbContext db)
        {
            _db = db;
        }

        [Authorize(Roles = "admin, moderator, user")]
        public IActionResult Index()
        {
            IEnumerable<Platform> objList = _db.Platforms;
            return View(objList);
        }

        //get-request?
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            return View();
        }


        //post-request??
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin")]
        public IActionResult Create(Platform obj)
        {
            if (ModelState.IsValid)
            {
                _db.Platforms.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET Delete
        [Authorize(Roles = "admin")]
        public IActionResult Delete(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Platforms.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);

        }

        // POST Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.Platforms.Find(id);
            if (obj == null)
            {
                return NotFound();
            }

            _db.Platforms.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }

        // GET Update
        [Authorize(Roles = "admin , moderator")]
        public IActionResult Update(int? id)
        {

            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Platforms.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);

        }

        // POST UPDATE
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "admin , moderator")]
        public IActionResult Update(Platform obj)
        {
            if (ModelState.IsValid)
            {
                _db.Platforms.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);

        }
    }
}

Views/Platform/Create.cshtml
@model Game.Models.Platform

<form method="post" asp-action="Create">
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Добавить платформу</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="PlatfromName"></label>
                        <input asp-for="PlatfromName" class="form-control" />
                        <span asp-validation-for="PlatfromName" class="text-danger"></span>
                    </div>
                    <div class="col-6">
                        <label asp-for="Tickrate"></label>
                        <input asp-for="Tickrate" class="form-control" />
                        <span asp-validation-for="Tickrate" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Back</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Platform/Delete.cshtml
@model Game.Models.Platform

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Удалить платформу</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="Tickrate"></label>
                    </div>
                                    </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="Tickrate" class="form-control" />
                        <span asp-validation-for="Tickrate" class="text-danger"></span>
                    </div>
                 </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-75" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-75">Назад</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Platform/Index.cshtml
@model IEnumerable<Game.Models.Platform>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Список платформ</h2>
        </div>
        @if(User.IsInRole("admin") || User.IsInRole("moderator"))
        {
        <div class="col-6 text-right">
            <a asp-controller="Platform" asp-action="Create" class="btn btn-primary">Добавить платформу</a>
        </div>
        }
    </div>
    <br />

    @if(Model.Count() > 0)
    {
    <table class="table table-bordered table-striped" style="width:100%">
        <thead>
            <tr>
                <th>
                    Название платформы
                </th>
                <th>
                    Тикрейт
                </th>
                <th>
                    Действия
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach(var obgect in Model)
            {
            <tr>
                <td width="40%">@obgect.PlatfromName</td>
                <td width="40%">@obgect.Tickrate</td>
                @if(User.IsInRole("admin") || User.IsInRole("moderator"))
                {
                <td width="25%">
                    <div class="w-100 btn-group" role="group">
                        <a asp-controller="Platform" asp-action="Update" asp-route-Id="@obgect.Id" class="btn btn-primary mx-1">Изменить</a>
                        <a asp-controller="Platform" asp-action="Delete" asp-route-Id="@obgect.Id" class="btn btn-danger mx-1">Удалить</a>
                    </div>
                </td>
                }
            </tr>
            }
        </tbody>
    </table>
    }
    else
    {
    <p>Ничего нет</p>
    }

</div>

Views/Platform/Update.cshtml
@model Game.Models.Platform

<form method="post" asp-action="Update">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Обновить платформу</h2>
        </div>
        <div class="col-6">
            <label asp-for="PlatfromName"></label>
            <input asp-for="PlatfromName" class="form-control" />
            <span asp-validation-for="PlatfromName" class="text-danger"></span>
        </div>
        <div class="col-6">
            <label asp-for="Tickrate"></label>
            <input asp-for="Tickrate" class="form-control" />
            <span asp-validation-for="Tickrate" class="text-danger"></span>
        </div>
        <div class="container">
            <div class="row">
                <div class="col">
                    <input type="submit" class="btn btn-info w-75" value="Update" />
                </div>
                <div class="col">
                    <a asp-action="Index" class="btn btn-danger w-75">Back</a>
                </div>
            </div>
        </div>

    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}